apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongo.config.name }}
  labels:
    app: {{ .Values.mongo.config.name }}
data: 
{{- range .Values.mongo.config.data }}
  {{ .key }}: {{ .value | quote }}
{{- end }}
