apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mongo.name }}
  name: {{ .Values.mongo.name }}
spec:
  ports:
    - name: {{ .Values.mongo.service.portName | quote }}
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  selector:
    service: {{ .Values.mongo.name | quote }}
status:
  loadBalancer: {}
