version: "3"
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  order:
    build: ./order
    restart: always
    hostname: order
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  payment:
    build: ./payment
    restart: always
    hostname: payment
    env_file:
      - .env
    networks:
      - backend
  db:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_MY_DATABASE}
    volumes:
      - "./db/home/mongodb:/home/mongodb"
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    name: infra
