kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv0
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: db-claim0
  local:
    path: "/db/home/mongodb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
