apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: order
    spec:
      containers:
        - env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  key: API_PORT
                  name: env
            - name: MONGO_MY_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_MY_DATABASE
                  name: env
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PASSWORD
                  name: env
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_ROOT_PASSWORD
                  name: env
            - name: MONGO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_ROOT_USER
                  name: env
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URL
                  name: env
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_USER
                  name: env
            - name: ORDER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE_HOST
                  name: env
            - name: ORDER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE_PORT
                  name: env
            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_HOST
                  name: env
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_PORT
                  name: env
          image: kenchoong012/setel:order
          imagePullPolicy: IfNotPresent
          name: order
          resources: {}
      hostname: order
      restartPolicy: Always
status: {}
